### PR TITLE
some typos and a redundant/repeated sentence

### PR DESCRIPTION
**Pull request by Sasja**

### CODE REVIEW

**Comment by galgalesh** [comment]
Thanks!


Before we can merge these, they must be accepted during a general assembly.
Can you put this on the agenda since I won't be there..?

Op woensdag 6 april 2016 heeft Sasja <notifications@github.com> het
volgende geschreven:
> ________________________________
>
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/0x20/HTH/pull/4
>
> Commit Summary
>
> some typos and a redundant/repeated sentence
>
> File Changes
>
> M README.md (15)
>
> Patch Links:
>
> https://github.com/0x20/HTH/pull/4.patch
> https://github.com/0x20/HTH/pull/4.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub<
https://ci5.googleusercontent.com/proxy/kk3EGtiuon02u-_oRJYcsidodbmFlpqi0kc0BvXMRfwi_vfvBeSDBRwkpMLzaknChF4GT7-AwDrWcoBOLB1pO4z5NjYqkuQO3IlHs6FOatjtw77v-g24cBDNktL4yEOehLPCixzy4T2P4Dd9b3gn7tjpPh-vBg=s0-d-e1-ft#https://github.com/notifications/beacon/ABbH9Tj4QgYPFol6QbIJs1sq7JPlSvgDks5p07RWgaJpZM4IBE8P.gif
>

**Comment by Sasja** [comment]
sure, but its just some minor stuff i ran into while reading it over, when is the general assembly?

**Comment by galgalesh** [comment]
I know it's silly having to approve such small updates, but that's what the
rules say. Feel free to propose a change in the rules to better handle typo
fixes..

Els announced GE on the mailinglist. 21 of april I think.

Op woensdag 6 april 2016 heeft Sasja <notifications@github.com> het
volgende geschreven:
> sure, but its just some minor stuff i ran into while reading it over,
when is the general assembly?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub<
https://ci6.googleusercontent.com/proxy/0-0Ay24g2IgYCZvj0rbzodZjmHdnWTFLQ1CWjX2cWoXGWQfCpwno850k67BFvGguxjTnv14AhZYRrzPzrOCKBOElA4Ma2UuWxYBQzklHrli5FP1VFsymczmrPtHKYkC_ksAwh2bm51q9_Fvfl5PH_zDMbjbsZg=s0-d-e1-ft#https://github.com/notifications/beacon/ABbH9RWuo8TI8t2n2LU8O4qzmlPSCfItks5p08sSgaJpZM4IBE8P.gif
>

**Comment by Sasja** [comment]
ok thanks, ill try and bring it up :)

**Pull request merged**
